name: Rust CI

on:
  push:
    branches:
      - aggregator-release
      - aggregator-dev
  pull_request:
    branches:
      - aggregator-release
      - aggregator-dev

jobs:
  test:
    name: Rust Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ./target
            !./target/doc
          key: ${{ runner.os }}-agg-${{ hashFiles('./Cargo.lock', './Cargo.toml') }}
      - run: cargo test
