name: Rust CI

on:
  push:
    branches:
      - maintenance-release
      - maintenance-dev
  pull_request:
    branches:
      - maintenance-release
      - maintenance-dev

jobs:
  test:
    name: Rust Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
